RegisterNetEvent("BASE:missiontext")
AddEventHandler("BASE:missiontext", function(text, time)
        ClearPrints()
        SetTextEntry_2("STRING")
        AddTextComponentString(text)
        DrawSubtitleTimed(time, 1)
end)